### ISSUE TITLE
Incorrectly parse pseudo-class selectors

### ISSUE THREAD

**Issue by Semigradsky** [isellsoap/specificity-visualizer#15]
CSS code:
```css
.foo :is(.bar, #baz) {}
```

Shows:
1. Selector: `.foo :is(.bar`, Specificity: `0,3,0`
1. Selector: ` #baz)`, Specificity: `1,0,0`

Expected result:
1. Selector: `.foo :is(.bar, #baz)`, Specificity: `1,1,0`

---
UPD: the same for other pseudo-classes: `:where`, `:nth-child`, `:not`, `:has`

**Comment by isellsoap** [comment]
Thanks, will investigate.

**Comment by Semigradsky** [comment]
@isellsoap Suggestion: you can take a look on [`parsel`](https://github.com/LeaVerou/parsel). This tool can parse and calculate specificity almost for all modern selectors (I know only one issue - https://github.com/LeaVerou/parsel/issues/12). [`specificity`](https://github.com/keeganstreet/specificity) as I see doesn't support modern selectors.

**Comment by isellsoap** [comment]
Thanks for the hint!

Generally speaking I would love to update this repo (it hasn’t really been updated for years). Let’s see if I can find the time to modernize things… ;)

**Comment by isellsoap** [comment]
Fixed. Thanks again. Using parsel now.

God, the code looks so aweful, could be done much better. I only touched the necessary parts to fix this issue. ;)
