### ISSUE TITLE
Add blog post explaining the tool

### ISSUE THREAD

**Issue by isellsoap** [isellsoap/specificity-visualizer#3]
See issue title.

**Comment by dimbak** [comment]
Hi, nice tool, you can consider adding bad and good examples :)

**Comment by isellsoap** [comment]
Will do. Thanks a lot for the input. The article is already in the makings… 🤓

**Comment by isellsoap** [comment]
Done -> https://francescoschwarz.de/en/blog/introducing-the-specificity-visualizer/
